# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, linux]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: pull latest code
        uses: actions/checkout@v1
      # - name: 配置环境
      #   uses: actions/setup-node@v1
      #   with: 
      #     node-version: ${{ matrix.node_version }}
      - name: install gatsby-cli
        run: yarn install -g gatsby-cli
      - name: install dependencies
        run: yarn
      - name: remove original static files
        run: rm -Rf ./public
      - name: rebuild gatsby page
        run: gatsby build
        shell: bash
